import { BaseSocialCollector } from './BaseSocialCollector.js';
import { getSecret } from '../../lib/settingsStore.js';

const UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const IG_APP_ID='936619743392459';
const MAX_REELS_PER_ACCOUNT=3;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function num(v){const n=Number(v);return Number.isFinite(n)?n:0;}
function first(...v){return v.find(x=>x!==undefined&&x!==null&&String(x).trim()!=='');}
function captionFrom(node){const edge=node?.edge_media_to_caption?.edges?.[0]?.node?.text;return String(first(edge,node?.caption?.text,node?.caption,node?.text,node?.description,'')||'');}
function videoUrlFrom(node){const versions=node?.video_versions||node?.videoVersions||[];return String(first(node?.video_url,node?.videoUrl,versions?.[0]?.url,'')||'');}
function imageUrlFrom(node){return String(first(node?.image_versions2?.candidates?.[0]?.url,node?.display_url,node?.thumbnail_url,'')||'');}
function normalizeNode(node,username){const shortcode=String(first(node?.code,node?.shortcode,node?.pk,node?.id,'')||'').trim();if(!shortcode)return null;const isReel=String(node?.product_type||node?.productType||'').toLowerCase()==='clips'||Boolean(node?.clips_metadata)||Boolean(node?.video_versions)||node?.media_type===2;if(!isReel)return null;const videoUrl=videoUrlFrom(node);if(!videoUrl)return null;return {externalPostId:shortcode,sourceUrl:`https://www.instagram.com/reel/${shortcode}/`,videoUrl,thumbnailUrl:imageUrlFrom(node),caption:captionFrom(node),authorId:String(first(node?.user?.pk,node?.owner?.id,'')||''),authorName:String(first(node?.user?.username,node?.owner?.username,username)||username),publishedAt:first(node?.taken_at,node?.taken_at_timestamp,null),views:num(first(node?.play_count,node?.video_play_count,node?.video_view_count,node?.view_count,0)),likes:num(first(node?.like_count,node?.edge_media_preview_like?.count,0)),comments:num(first(node?.comment_count,node?.edge_media_to_comment?.count,0)),shares:num(first(node?.reshare_count,node?.share_count,0)),metadata:{source:'instagram-session',raw:node}};}
function score(x){const s=String(x?.caption||'').toLowerCase();let cue=0;if(/프로필|링크|인포크|구매|제품|상품|공구|추천|쿠팡/.test(s))cue+=5000;if(/댓글|검색|궁금|정보|템|꿀템|살림|주방|수납|생활|차량|육아|반려|레시피/.test(s))cue+=2500;return cue+num(x?.views)*.02+num(x?.likes)*4+num(x?.comments)*3+num(x?.shares)*5;}
function sessionHeaders(){const sessionid=String(getSecret('INSTAGRAM_SESSION_ID')||'').trim();const csrf=String(getSecret('INSTAGRAM_CSRF_TOKEN')||'').trim();if(!sessionid)throw new Error('Instagram Session ID가 설정되어 있지 않습니다. 관리자 설정에 sessionid를 저장해 주세요.');const cookie=[`sessionid=${sessionid}`,csrf?`csrftoken=${csrf}`:''].filter(Boolean).join('; ');return {'user-agent':UA,'accept':'*/*','accept-language':'ko-KR,ko;q=0.9,en-US;q=0.7','x-ig-app-id':IG_APP_ID,'x-requested-with':'XMLHttpRequest','referer':'https://www.instagram.com/','cookie':cookie,...(csrf?{'x-csrftoken':csrf}:{})};}
async function igJson(url){await sleep(700);const r=await fetch(url,{headers:sessionHeaders(),redirect:'follow',signal:AbortSignal.timeout(20000)});const text=await r.text();if(r.status===401||r.status===403)throw new Error('Instagram 로그인 세션이 만료되었거나 사용할 수 없습니다. sessionid를 다시 저장해 주세요.');if(r.status===429)throw new Error('Instagram 세션 요청이 일시적으로 제한되었습니다(429). 잠시 후 다시 실행해 주세요.');if(!r.ok)throw new Error(`Instagram session HTTP ${r.status}: ${text.slice(0,180)}`);try{return JSON.parse(text||'{}');}catch{throw new Error('Instagram 세션 응답이 JSON이 아닙니다. 세션 만료 가능성이 있습니다.');}}
async function collectAccount(username){const profileUrl=new URL('https://www.instagram.com/api/v1/users/web_profile_info/');profileUrl.searchParams.set('username',username);const profile=await igJson(profileUrl.toString());const user=profile?.data?.user||profile?.user||{};const userId=String(first(user?.id,user?.pk,'')||'');const out=[];for(const bucket of [user?.edge_felix_video_timeline?.edges,user?.edge_owner_to_timeline_media?.edges,user?.edge_clips_grid?.edges])for(const e of bucket||[]){const x=normalizeNode(e?.node||e?.media||e,username);if(x)out.push(x);}if(userId){const feed=await igJson(`https://www.instagram.com/api/v1/feed/user/${encodeURIComponent(userId)}/?count=12`);for(const raw of feed?.items||[]){const x=normalizeNode(raw?.media||raw,username);if(x)out.push(x);}}const uniq=new Map();for(const x of out)if(x?.externalPostId&&!uniq.has(x.externalPostId))uniq.set(x.externalPostId,x);return [...uniq.values()].sort((a,b)=>score(b)-score(a)).slice(0,MAX_REELS_PER_ACCOUNT);}
export class DirectInstagramCollector extends BaseSocialCollector{constructor(){super('INSTAGRAM');}async discover(target){const username=String(target?.target_value||'').replace(/^@/,'').trim();if(!username)return [];console.log(`[InstagramDirect] collect start account=${username} mode=SESSION`);const items=await collectAccount(username);console.log(`[InstagramDirect] collect done account=${username} selected=${items.length}`);if(!items.length)throw new Error('Instagram 로그인 세션으로 Reel을 찾지 못했습니다. 계정 공개 여부와 sessionid 상태를 확인해 주세요.');return items;}}
