import { callOpenAiJson } from '../../lib/openAiJsonClient.js';
const UA='Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Mobile Safari/537.36';
function decodeHtml(s=''){return String(s).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
function stripTags(s=''){return decodeHtml(String(s).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());}
function normalizeText(s=''){return String(s).toLowerCase().replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();}
function tokens(s=''){return new Set(normalizeText(s).split(' ').filter(x=>x.length>1));}
function scoreText(q,t){const a=tokens(q),b=tokens(t);if(!a.size||!b.size)return 0;return Math.round([...a].filter(x=>b.has(x)).length/Math.max(1,Math.min(a.size,b.size))*100);}
function normalizeUrl(value=''){let s=decodeHtml(String(value||'').trim()).replace(/^['"]+|['"]+$/g,'').replace(/\\u0026/g,'&').replace(/\\\//g,'/');if(!s)return'';if(/^\/\//.test(s))s=`https:${s}`;else if(!/^[a-z][a-z0-9+.-]*:\/\//i.test(s)&&/^[\w.-]+\.[a-z]{2,}/i.test(s))s=`https://${s}`;try{return new URL(s).toString();}catch{return s;}}
function collectUrls(obj,out=[],depth=0){if(depth>7||obj==null)return out;if(typeof obj==='string'){const raw=String(obj).replace(/\\u0026/g,'&').replace(/\\\//g,'/');for(const m of raw.matchAll(/https?:\/\/[^\s"'<>]+/g)){const u=normalizeUrl(m[0]);if(u)out.push(u);}return out;}if(Array.isArray(obj)){for(const v of obj)collectUrls(v,out,depth+1);}else if(typeof obj==='object')for(const v of Object.values(obj))collectUrls(v,out,depth+1);return out;}
export function findInpockUrlInMetadata(metadata){return collectUrls(metadata).find(u=>/(?:link\.inpock\.co\.kr|moneying\.biz\/link\/gooditem)/i.test(u))||'';}
export async function detectInpockProfileUrl(username,metadata={}){const fromMeta=normalizeUrl(findInpockUrlInMetadata(metadata));if(fromMeta)return fromMeta;const user=String(username||'').replace(/^@/,'').trim();if(!user)return'';try{const r=await fetch(`https://www.instagram.com/${encodeURIComponent(user)}/`,{headers:{'user-agent':UA,'accept-language':'ko-KR,ko;q=0.9,en;q=0.7'},redirect:'follow',signal:AbortSignal.timeout(15000)});const raw=(await r.text()).replace(/\\u0026/g,'&').replace(/\\\//g,'/');return normalizeUrl(raw.match(/(?:https?:\/\/)?(?:link\.inpock\.co\.kr|moneying\.biz\/link\/gooditem)[A-Za-z0-9_?=&%./:-]*/i)?.[0]||'');}catch{return'';}}
// OpenAI STT is intentionally disabled. Product analysis must continue from caption, frames/Lens and OCR.
export async function transcribeVideoAudio(){console.log('[Instagram][TRANSCRIBE] skipped - Gemini/visual-first pipeline');return '';}
export async function rewriteInstagramScript({caption='',transcript='',productName=''}){const result=await callOpenAiJson({system:'너는 짧은 한국어 쇼핑 릴스 대본 작가다. 원문의 사실과 제품 사용 맥락만 참고하고 문장 구조와 표현은 새로 쓴다. 과장·허위 표현을 만들지 않는다. JSON만 반환한다.',user:`Instagram Reel 본문:\n${caption}\n\n참고 텍스트:\n${transcript}\n\n확정 또는 후보 상품:\n${productName}\n\n15~25초 분량의 자연스러운 한국어 대본으로 다시 작성해라. 반환 JSON: {"hook":"","body":"","ending":"","fullScript":"","searchKeywords":[""]}`});if(!result.fullScript)result.fullScript=[result.hook,result.body,result.ending].filter(Boolean).join(' ');return result;}
async function fetchInpockCatalog(inpockUrl){const u=normalizeUrl(inpockUrl);if(!u)return[];const r=await fetch(u,{headers:{'user-agent':UA,'accept-language':'ko-KR,ko;q=0.9'},redirect:'follow',signal:AbortSignal.timeout(20000)});const html=await r.text();if(!r.ok)throw new Error(`인포크 페이지 오류 (${r.status})`);const items=[];for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){let href=normalizeUrl(decodeHtml(m[1]));const title=stripTags(m[2]);try{href=new URL(href,r.url).toString();}catch{}if(/^https?:\/\//i.test(href)&&title)items.push({title,href});}const seen=new Set();return items.filter(x=>{const k=x.title+'|'+x.href;if(seen.has(k))return false;seen.add(k);return true;});}
async function resolveFinalUrl(url){const u=normalizeUrl(url);if(!u)return'';try{const r=await fetch(u,{headers:{'user-agent':UA},redirect:'follow',signal:AbortSignal.timeout(15000)});return r.url||u;}catch{return u;}}
function isCanonicalCoupangProductUrl(url=''){try{const u=new URL(normalizeUrl(url));return /(^|\.)coupang\.com$/i.test(u.hostname)&&/^\/vp\/products\/\d+/i.test(u.pathname);}catch{return false;}}
export async function matchInpockProduct({inpockUrl,caption='',transcript='',rewrittenScript=null}){const u=normalizeUrl(inpockUrl);if(!u)return null;const catalog=await fetchInpockCatalog(u);if(!catalog.length)return null;const explicit=[caption,transcript,...(rewrittenScript?.searchKeywords||[])].filter(Boolean).join(' ');const ranked=catalog.map(x=>({...x,score:scoreText(explicit,x.title)})).sort((a,b)=>b.score-a.score);const best=ranked.find(x=>x.score>=35)||ranked.find(x=>/coupang|link\.coupang/i.test(x.href));if(!best)return null;const finalUrl=await resolveFinalUrl(best.href);return{...best,finalUrl,isCoupang:isCanonicalCoupangProductUrl(finalUrl),catalogCount:catalog.length};}
