import express from 'express';
import path from 'node:path';
import fs from 'node:fs';
import { db } from '../db/db.js';
import { newId, contentHash, normalizeTopic } from '../lib/util.js';
import { getSecret } from '../lib/settingsStore.js';
import { downloadSocialVideo } from '../modules/media/SocialMediaDownloader.js';
import { cleanChineseSubtitles } from '../modules/media/SubtitleCleaner.js';
import { extractBestFrames } from '../modules/productIdentification/FrameExtractor.js';
import { searchLens } from '../modules/productIdentification/LensService.js';
import { resolveProduct, scoreCoupangCandidate } from '../modules/productIdentification/ProductResolver.js';
import { searchCoupangProducts, createCoupangDeepLink } from '../modules/productIdentification/CoupangPartnersClient.js';
import { detectInpockProfileUrl, transcribeVideoAudio, rewriteInstagramScript, matchInpockProduct } from '../modules/social/InstagramContentService.js';
import { runPipeline } from '../workers/pipelineWorker.js';
import { runInstagramRemixPipeline } from '../workers/instagramRemixPipeline.js';

export const discoveryRouter=express.Router();
const VALID_PLATFORMS=new Set(['DOUYIN','XIAOHONGSHU','INSTAGRAM']);
const VALID_TYPES=new Set(['ACCOUNT','HASHTAG','KEYWORD']);
function log(post,stage,reason='',attempt=1){db.prepare('INSERT INTO social_job_logs(id,post_id,platform,stage,reason,attempt) VALUES(?,?,?,?,?,?)').run(newId('log'),post?.id||null,post?.platform||null,stage,String(reason||''),attempt);console.log(`[Discovery][${stage}] post=${post?.id||'-'} ${reason||''}`);}
function publicFrameUrl(file){const base=String(getSecret('PUBLIC_BASE_URL')||process.env.PUBLIC_BASE_URL||'').replace(/\/$/,'');if(!base)return '';const root=path.resolve(process.env.STORAGE_ROOT||'./storage');const rel=path.relative(root,path.resolve(file)).split(path.sep).map(encodeURIComponent).join('/');return `${base}/storage/${rel}`;}
function thresholdStatus(score){return score>=90?'AUTO_CONFIRMED':score>=70?'REVIEW_REQUIRED':'REJECTED';}
function subId(){return getSecret('COUPANG_SUB_ID')||process.env.COUPANG_SUB_ID||'';}
function parseMeta(post){try{return JSON.parse(post.metadata_json||'{}')}catch{return {}}}
function saveMeta(postId,meta){db.prepare('UPDATE social_posts SET metadata_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(JSON.stringify(meta),postId);}

discoveryRouter.get('/targets',(_req,res)=>{const items=db.prepare(`SELECT t.*,a.inpock_url FROM social_monitor_targets t LEFT JOIN instagram_benchmark_accounts a ON a.target_id=t.id ORDER BY t.created_at DESC`).all();res.json({items});});
discoveryRouter.post('/targets',(req,res)=>{try{let platform=String(req.body?.platform||'').toUpperCase(),targetType=String(req.body?.targetType||'').toUpperCase(),targetValue=String(req.body?.targetValue||'').trim();if(platform==='INSTAGRAM'){targetType='ACCOUNT';targetValue=targetValue.replace(/^@/,'');}if(!VALID_PLATFORMS.has(platform)||!VALID_TYPES.has(targetType)||!targetValue)return res.status(400).json({error:'platform/targetType/targetValue를 확인해 주세요.'});const id=newId('target');db.prepare('INSERT INTO social_monitor_targets(id,platform,target_type,target_value,enabled) VALUES(?,?,?,?,1)').run(id,platform,targetType,targetValue);if(platform==='INSTAGRAM')db.prepare('INSERT OR REPLACE INTO instagram_benchmark_accounts(id,target_id,username,inpock_url,profile_url,enabled) VALUES(?,?,?,?,?,1)').run(newId('iga'),id,targetValue,String(req.body?.inpockUrl||'').trim(),`https://www.instagram.com/${targetValue}/`);res.json(db.prepare('SELECT * FROM social_monitor_targets WHERE id=?').get(id));}catch(err){res.status(400).json({error:String(err.message||err)});}});
discoveryRouter.patch('/targets/:id',(req,res)=>{const enabled=req.body?.enabled?1:0;const r=db.prepare('UPDATE social_monitor_targets SET enabled=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(enabled,req.params.id);db.prepare('UPDATE instagram_benchmark_accounts SET enabled=?,updated_at=CURRENT_TIMESTAMP WHERE target_id=?').run(enabled,req.params.id);if(!r.changes)return res.status(404).json({error:'not found'});res.json({ok:true});});

discoveryRouter.post('/ingest',(req,res)=>{try{const x=req.body||{};const platform=String(x.platform||'').toUpperCase();if(!VALID_PLATFORMS.has(platform)||!x.externalPostId||!x.sourceUrl)return res.status(400).json({error:'platform, externalPostId, sourceUrl이 필요합니다.'});const existing=db.prepare('SELECT * FROM social_posts WHERE platform=? AND external_post_id=?').get(platform,String(x.externalPostId));if(existing)return res.json({item:existing,duplicate:true});const id=newId('post');db.prepare(`INSERT INTO social_posts(id,target_id,platform,external_post_id,author_id,author_name,source_url,caption,published_at,views,likes,comments,shares,video_url,thumbnail_url,status,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,x.targetId||null,platform,String(x.externalPostId),x.authorId||'',x.authorName||'',x.sourceUrl,x.caption||'',x.publishedAt||null,Number(x.views||0),Number(x.likes||0),Number(x.comments||0),Number(x.shares||0),x.videoUrl||'',x.thumbnailUrl||'','DISCOVERED',JSON.stringify(x.metadata||{}));const post=db.prepare('SELECT * FROM social_posts WHERE id=?').get(id);log(post,'DISCOVERED');res.json({item:post,duplicate:false});}catch(err){res.status(400).json({error:String(err.message||err)});}});

discoveryRouter.get('/posts',(req,res)=>{const status=String(req.query.status||'').trim();const items=status?db.prepare('SELECT * FROM social_posts WHERE status=? ORDER BY created_at DESC LIMIT 100').all(status):db.prepare('SELECT * FROM social_posts ORDER BY created_at DESC LIMIT 100').all();res.json({items});});
discoveryRouter.get('/posts/:id',(req,res)=>{const post=db.prepare('SELECT * FROM social_posts WHERE id=?').get(req.params.id);if(!post)return res.status(404).json({error:'not found'});const frames=db.prepare('SELECT * FROM video_frames WHERE post_id=? ORDER BY visual_score DESC').all(post.id);const candidate=db.prepare('SELECT * FROM product_candidates WHERE post_id=? ORDER BY created_at DESC LIMIT 1').get(post.id);const matches=candidate?db.prepare('SELECT * FROM coupang_matches WHERE candidate_id=? ORDER BY score DESC').all(candidate.id):[];const jobs=db.prepare('SELECT * FROM content_jobs WHERE post_id=? ORDER BY created_at DESC').all(post.id);res.json({post:{...post,metadata:parseMeta(post)},frames,candidate,matches,jobs});});

async function buildLens(post,videoPath,count){db.prepare('DELETE FROM video_frames WHERE post_id=?').run(post.id);const frames=extractBestFrames({postId:post.id,videoPath,count});const lensResults=[];for(const f of frames){const frameId=newId('frame'),url=publicFrameUrl(f.filePath);let lens=null;if(url){try{lens=await searchLens(url);lensResults.push(lens);}catch(err){log(post,'LENS_FAILED',err.message);}}db.prepare('INSERT INTO video_frames(id,post_id,timestamp,local_path,public_url,file_size,visual_score,is_selected,lens_json) VALUES(?,?,?,?,?,?,?,?,?)').run(frameId,post.id,f.timestamp,f.filePath,url,f.size,f.visualScore,1,lens?JSON.stringify(lens):null);}return lensResults;}
function insertCandidate(post,resolved){const id=newId('candidate');db.prepare(`INSERT INTO product_candidates(id,post_id,product_type,brand,model,material,color,features_json,usage_text,korean_name,search_queries_json,resolver_confidence,status,raw_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,post.id,resolved.productType||'',resolved.brand||'',resolved.model||'',resolved.material||'',resolved.color||'',JSON.stringify(resolved.features||[]),resolved.usage||'',resolved.koreanName||'',JSON.stringify(resolved.searchQueries||[]),Number(resolved.confidence||0),'PRODUCT_FOUND',JSON.stringify(resolved));return id;}
async function insertDirectInpockMatch(post,candidateId,inpock,resolved){let affiliate='';try{const d=await createCoupangDeepLink(inpock.finalUrl,{subId:subId()});affiliate=d?.shortenUrl||d?.landingUrl||inpock.finalUrl;}catch(err){log(post,'DEEPLINK_FAILED',err.message);}const id=newId('match');db.prepare('INSERT INTO coupang_matches(id,candidate_id,product_id,product_name,product_price,product_url,product_image,rank,score,status,affiliate_url,raw_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,candidateId,'',inpock.title||resolved.koreanName||'인포크 연결 상품',0,inpock.finalUrl,'',1,100,'AUTO_CONFIRMED',affiliate,JSON.stringify(inpock));return {id,productName:inpock.title||resolved.koreanName,productUrl:inpock.finalUrl,score:100,status:'AUTO_CONFIRMED',affiliateUrl:affiliate};}
async function fallbackCoupang(post,candidateId,resolved){const seen=new Map();for(const q of (resolved.searchQueries||[]).slice(0,3)){for(const p of await searchCoupangProducts(q,{limit:10,subId:subId()}))if(!seen.has(String(p.productId)))seen.set(String(p.productId),p);}const scored=[...seen.values()].map(p=>({...p,score:scoreCoupangCandidate(resolved,p)})).sort((a,b)=>b.score-a.score).slice(0,20);for(const p of scored){const status=thresholdStatus(p.score);let affiliateUrl='';if(status==='AUTO_CONFIRMED'){try{const d=await createCoupangDeepLink(p.productUrl,{subId:subId()});affiliateUrl=d?.shortenUrl||d?.landingUrl||p.productUrl||'';}catch(err){log(post,'DEEPLINK_FAILED',err.message);}}db.prepare('INSERT INTO coupang_matches(id,candidate_id,product_id,product_name,product_price,product_url,product_image,rank,score,status,affiliate_url,raw_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(newId('match'),candidateId,String(p.productId||''),p.productName||'',Number(p.productPrice||0),p.productUrl||'',p.productImage||'',Number(p.rank||0),p.score,status,affiliateUrl,JSON.stringify(p));}return scored;}

async function analyzeInstagram(post,originalPath,reqBody){const meta=parseMeta(post);let transcript='';try{transcript=await transcribeVideoAudio({postId:post.id,videoPath:originalPath});log(post,'INSTAGRAM_TRANSCRIBED',`chars=${transcript.length}`);}catch(err){log(post,'INSTAGRAM_TRANSCRIBE_FAILED',err.message);}let inpock=db.prepare('SELECT inpock_url FROM instagram_benchmark_accounts WHERE target_id=?').get(post.target_id)?.inpock_url||'';if(!inpock)inpock=await detectInpockProfileUrl(post.author_name,meta);if(inpock)db.prepare('UPDATE instagram_benchmark_accounts SET inpock_url=?,last_inpock_checked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE target_id=?').run(inpock,post.target_id);let rewritten=await rewriteInstagramScript({caption:post.caption||'',transcript,productName:''});let inpockMatch=null;try{inpockMatch=await matchInpockProduct({inpockUrl:inpock,caption:post.caption||'',transcript,rewrittenScript:rewritten});if(inpockMatch)log(post,'INPOCK_MATCH',`${inpockMatch.score} ${inpockMatch.title}`);}catch(err){log(post,'INPOCK_FAILED',err.message);}let lensResults=[];if(!inpockMatch?.isCoupang)lensResults=await buildLens(post,originalPath,1);const resolved=await resolveProduct({caption:post.caption||'',transcript,ocrText:String(reqBody?.ocrText||''),lensResults});rewritten=await rewriteInstagramScript({caption:post.caption||'',transcript,productName:inpockMatch?.title||resolved.koreanName||''});const candidateId=insertCandidate(post,resolved);let matches=[];if(inpockMatch?.isCoupang)matches=[await insertDirectInpockMatch(post,candidateId,inpockMatch,resolved)];else matches=await fallbackCoupang(post,candidateId,resolved);const metadata={...meta,instagram:{transcript,rewrittenScript:rewritten,inpockUrl:inpock,inpockMatch}};saveMeta(post.id,metadata);try{const clean=cleanChineseSubtitles({postId:post.id,inputPath:originalPath,mode:'DELOGO'});log(post,'TEXT_OVERLAY_CLEANED',clean.outputPath);}catch(err){log(post,'TEXT_OVERLAY_CLEAN_FAILED',err.message);}const top=db.prepare('SELECT * FROM coupang_matches WHERE candidate_id=? ORDER BY score DESC LIMIT 1').get(candidateId);const status=top?.status||'PRODUCT_NOT_FOUND';db.prepare('UPDATE social_posts SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,post.id);return {resolved,matches,status,instagram:metadata.instagram};}

discoveryRouter.post('/posts/:id/analyze',async(req,res)=>{const post=db.prepare('SELECT * FROM social_posts WHERE id=?').get(req.params.id);if(!post)return res.status(404).json({error:'not found'});try{db.prepare("UPDATE social_posts SET status='DOWNLOADING',error_message=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(post.id);const isInstagram=post.platform==='INSTAGRAM';const videoPath=post.local_video_path&&fs.existsSync(post.local_video_path)?post.local_video_path:await downloadSocialVideo({postId:post.id,url:post.video_url,platform:post.platform,sourceUrl:post.source_url,cleanSubtitles:!isInstagram});db.prepare("UPDATE social_posts SET local_video_path=?,status='ANALYZING',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(videoPath,post.id);log(post,'DOWNLOADED');if(isInstagram){const result=await analyzeInstagram(post,videoPath,req.body||{});return res.json({ok:true,postId:post.id,candidate:result.resolved,matches:result.matches,status:result.status,instagram:result.instagram});}const lensResults=await buildLens(post,videoPath,3);const resolved=await resolveProduct({caption:post.caption||'',transcript:String(req.body?.transcript||''),ocrText:String(req.body?.ocrText||''),lensResults});const candidateId=insertCandidate(post,resolved);const scored=await fallbackCoupang(post,candidateId,resolved);const top=db.prepare('SELECT * FROM coupang_matches WHERE candidate_id=? ORDER BY score DESC LIMIT 1').get(candidateId);const status=top?.status||'PRODUCT_NOT_FOUND';db.prepare('UPDATE social_posts SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,post.id);log(post,status);res.json({ok:true,postId:post.id,candidate:resolved,matches:scored.slice(0,10),status});}catch(err){db.prepare("UPDATE social_posts SET status='ANALYSIS_FAILED',error_message=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(String(err.message||err),post.id);log(post,'ANALYSIS_FAILED',err.message);res.status(500).json({error:String(err.message||err)});}});

discoveryRouter.post('/matches/:id/confirm',async(req,res)=>{try{const m=db.prepare('SELECT m.*,c.post_id,c.korean_name,c.features_json FROM coupang_matches m JOIN product_candidates c ON c.id=m.candidate_id WHERE m.id=?').get(req.params.id);if(!m)return res.status(404).json({error:'not found'});let affiliate=m.affiliate_url;if(!affiliate){const d=await createCoupangDeepLink(m.product_url,{subId:subId()});affiliate=d?.shortenUrl||d?.landingUrl||m.product_url;}db.prepare("UPDATE coupang_matches SET status='AUTO_CONFIRMED',affiliate_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(affiliate,m.id);db.prepare("UPDATE coupang_matches SET status='REJECTED',updated_at=CURRENT_TIMESTAMP WHERE candidate_id=? AND id<>?").run(m.candidate_id,m.id);db.prepare("UPDATE social_posts SET status='AUTO_CONFIRMED',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(m.post_id);res.json({ok:true,affiliateUrl:affiliate});}catch(err){res.status(500).json({error:String(err.message||err)});}});

discoveryRouter.post('/matches/:id/create-short',(req,res)=>{try{const m=db.prepare('SELECT m.*,c.post_id,c.korean_name,c.features_json,p.source_url,p.platform,p.metadata_json FROM coupang_matches m JOIN product_candidates c ON c.id=m.candidate_id JOIN social_posts p ON p.id=c.post_id WHERE m.id=?').get(req.params.id);if(!m)return res.status(404).json({error:'not found'});if(m.status!=='AUTO_CONFIRMED')return res.status(400).json({error:'먼저 상품을 확정해 주세요.'});const topic=[m.korean_name,m.product_name].filter(Boolean).join(' - ');const projectId=newId('project');db.prepare('INSERT INTO shorts_projects(id,topic,source_url,source_type,voice_mode,normalized_topic,content_hash,status) VALUES(?,?,?,?,?,?,?,?)').run(projectId,topic,m.source_url,m.platform==='INSTAGRAM'?'INSTAGRAM_REEL':'SOCIAL_PRODUCT','AI_TTS',normalizeTopic(topic),contentHash(`${m.post_id}:${m.product_id}`),'QUEUED');const jobId=newId('job');db.prepare('INSERT INTO content_jobs(id,post_id,candidate_id,coupang_match_id,shorts_project_id,content_score,status) VALUES(?,?,?,?,?,?,?)').run(jobId,m.post_id,m.candidate_id,m.id,projectId,Number(req.body?.contentScore||85),'QUEUED');res.status(202).json({ok:true,projectId,jobId,status:'QUEUED'});setImmediate(async()=>{try{if(m.platform==='INSTAGRAM'){let meta={};try{meta=JSON.parse(m.metadata_json||'{}')}catch{}const script=meta?.instagram?.rewrittenScript?.fullScript||topic;await runInstagramRemixPipeline({projectId,postId:m.post_id,scriptText:script});}else await runPipeline(projectId);db.prepare("UPDATE content_jobs SET status='READY',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(jobId);}catch(err){db.prepare("UPDATE content_jobs SET status='FAILED',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(jobId);console.error('[discovery pipeline failed]',projectId,err);}});}catch(err){res.status(500).json({error:String(err.message||err)});}});

discoveryRouter.get('/dashboard',(_req,res)=>{const scalar=(sql)=>Number(db.prepare(sql).pluck().get()||0);res.json({targets:scalar('SELECT COUNT(*) FROM social_monitor_targets WHERE enabled=1'),posts:scalar('SELECT COUNT(*) FROM social_posts'),instagram:scalar("SELECT COUNT(*) FROM social_posts WHERE platform='INSTAGRAM'"),autoConfirmed:scalar("SELECT COUNT(*) FROM coupang_matches WHERE status='AUTO_CONFIRMED'"),reviewRequired:scalar("SELECT COUNT(*) FROM coupang_matches WHERE status='REVIEW_REQUIRED'"),contentJobs:scalar('SELECT COUNT(*) FROM content_jobs'),readyJobs:scalar("SELECT COUNT(*) FROM content_jobs WHERE status='READY'")});});
