import express from 'express';
import { db } from '../db/db.js';
import { getSecret } from '../lib/settingsStore.js';
import { runSocialMonitorOnce } from '../workers/socialMonitor.js';

export const discoveryAutoRouter=express.Router();
const runState={running:false,stage:'IDLE',message:'대기 중',startedAt:null,finishedAt:null,newPosts:0,totalPosts:0,queued:0,retryQueued:0,processed:0,succeeded:0,failed:0,currentPostId:null,lastError:null};
function localBase(){return `http://127.0.0.1:${process.env.PORT||4100}`;}
async function analyzePost(postId){console.log(`[DiscoveryAuto][ANALYZE] start post=${postId}`);const r=await fetch(`${localBase()}/api/discovery/posts/${encodeURIComponent(postId)}/analyze`,{method:'POST',headers:{'content-type':'application/json'},body:'{}',signal:AbortSignal.timeout(180000)});const text=await r.text();if(!r.ok){console.error(`[DiscoveryAuto][ANALYZE][FAILED] post=${postId} status=${r.status} reason=${text.slice(0,1200)}`);throw new Error(text||`분석 실패 (${r.status})`);}const parsed=JSON.parse(text||'{}');console.log(`[DiscoveryAuto][ANALYZE] success post=${postId} status=${parsed.status||'OK'} matches=${Array.isArray(parsed.matches)?parsed.matches.length:0}`);return parsed;}
function analysisQueue(postIds=[]){const ids=[...new Set((postIds||[]).map(String).filter(Boolean))].slice(0,3);if(!ids.length)return [];const placeholders=ids.map(()=>'?').join(',');return db.prepare(`SELECT id,status FROM social_posts WHERE platform='INSTAGRAM' AND COALESCE(video_url,'')<>'' AND status='DISCOVERED' AND id IN (${placeholders}) ORDER BY created_at DESC`).all(...ids);}
async function executeOneClick(){runState.running=true;runState.stage='COLLECTING';runState.message='Instagram 로그인 세션으로 상품 Reel 후보를 찾고 있습니다';runState.startedAt=new Date().toISOString();runState.finishedAt=null;runState.newPosts=0;runState.queued=0;runState.retryQueued=0;runState.processed=0;runState.succeeded=0;runState.failed=0;runState.currentPostId=null;runState.lastError=null;console.log('[DiscoveryAuto] Instagram session one-click started');try{const collected=await runSocialMonitorOnce();runState.newPosts=Number(collected.discovered||0);runState.totalPosts=Number(db.prepare("SELECT COUNT(*) FROM social_posts WHERE platform='INSTAGRAM'").pluck().get()||0);console.log(`[DiscoveryAuto] Instagram session collection done targets=${collected.targets} new=${runState.newPosts} total=${runState.totalPosts} failedTargets=${collected.failedTargets||0} pool=${collected.candidatePool||0}`);const posts=analysisQueue(collected.newPostIds);runState.queued=posts.length;runState.stage='ANALYZING';runState.message=posts.length?`이번 실행에서 선택한 상품 Reel ${posts.length}개만 분석하고 있습니다`:'이번 실행에서 새로 선택된 상품 Reel이 없습니다';console.log(`[DiscoveryAuto] analysis queue=${posts.length} new-only=yes`);for(const p of posts){runState.currentPostId=p.id;try{await analyzePost(p.id);runState.succeeded++;}catch(err){runState.failed++;runState.lastError=String(err?.message||err).slice(0,500);console.error(`[DiscoveryAuto] post failed post=${p.id} reason=${runState.lastError}`);}finally{runState.processed++;}}runState.stage='DONE';runState.message=`완료 · 새 상품 Reel ${runState.processed}개 처리 · 성공 ${runState.succeeded} · 실패 ${runState.failed}`;console.log(`[DiscoveryAuto] done processed=${runState.processed} success=${runState.succeeded} failed=${runState.failed}`);}catch(err){runState.stage='FAILED';runState.lastError=String(err?.message||err);runState.message=`자동 실행 실패 · ${runState.lastError}`;console.error(`[DiscoveryAuto][FAILED] ${runState.lastError}`,err);}finally{runState.running=false;runState.currentPostId=null;runState.finishedAt=new Date().toISOString();}}

discoveryAutoRouter.get('/status',(_req,res)=>{const instagramTargets=Number(db.prepare("SELECT COUNT(*) FROM social_monitor_targets WHERE enabled=1 AND platform='INSTAGRAM' AND target_type='ACCOUNT'").pluck().get()||0);const instagramSession=!!getSecret('INSTAGRAM_SESSION_ID');res.json({collectors:{INSTAGRAM_SESSION:instagramSession},ready:instagramTargets>0&&instagramSession,services:{instagramSession,openai:!!getSecret('OPENAI_API_KEY'),serpapi:!!getSecret('SERPAPI_API_KEY'),coupang:!!getSecret('COUPANG_ACCESS_KEY')&&!!getSecret('COUPANG_SECRET_KEY'),publicBaseUrl:!!getSecret('PUBLIC_BASE_URL')},activeTargets:instagramTargets,instagramTargets,posts:Number(db.prepare("SELECT COUNT(*) FROM social_posts WHERE platform='INSTAGRAM'").pluck().get()||0),run:{...runState}});});

discoveryAutoRouter.post('/run',(req,res)=>{const instagramTargets=Number(db.prepare("SELECT COUNT(*) FROM social_monitor_targets WHERE enabled=1 AND platform='INSTAGRAM' AND target_type='ACCOUNT'").pluck().get()||0);if(!instagramTargets)return res.status(503).json({error:'Instagram 벤치마킹 계정을 먼저 1개 이상 등록해 주세요.'});if(!getSecret('INSTAGRAM_SESSION_ID'))return res.status(503).json({error:'Instagram sessionid를 관리자 설정에 먼저 저장해 주세요.'});if(!getSecret('OPENAI_API_KEY'))return res.status(503).json({error:'OpenAI API Key를 먼저 저장해 주세요.'});if(!getSecret('SERPAPI_API_KEY'))return res.status(503).json({error:'SerpApi Key를 먼저 저장해 주세요.'});if(!getSecret('COUPANG_ACCESS_KEY')||!getSecret('COUPANG_SECRET_KEY'))return res.status(503).json({error:'쿠팡파트너스 Access Key와 Secret Key를 먼저 저장해 주세요.'});if(!getSecret('PUBLIC_BASE_URL'))return res.status(503).json({error:'Public Base URL을 먼저 저장해 주세요.'});if(runState.running)return res.status(409).json({error:'이미 자동 작업이 진행 중입니다.',run:{...runState}});setImmediate(()=>executeOneClick());res.status(202).json({ok:true,status:'STARTED',message:'Instagram 로그인 세션으로 전체 계정에서 상품성 높은 Reel 최대 3개를 골라 자동 분석합니다.'});});