import express from 'express';
import { db } from '../db/db.js';
import { newId } from '../lib/util.js';
import { getSecret } from '../lib/settingsStore.js';
import { runSocialMonitorOnce } from '../workers/socialMonitor.js';

export const discoveryAutoRouter=express.Router();
const DEFAULT_TARGETS={DOUYIN:['收纳神器','厨房神器','车载好物','家居好物','宠物用品'],XIAOHONGSHU:['收纳好物','家居好物','厨房好物','车载好物','生活好物']};
const MAX_ANALYSIS_FAILURES=3;
const runState={running:false,stage:'IDLE',message:'대기 중',startedAt:null,finishedAt:null,newPosts:0,totalPosts:0,queued:0,retryQueued:0,processed:0,succeeded:0,failed:0,currentPostId:null,lastError:null};
function collectorStatus(){const apify=Boolean(getSecret('APIFY_API_TOKEN'));return {APIFY:apify,DOUYIN:apify||Boolean(getSecret('DOUYIN_COLLECTOR_ENDPOINT')),XIAOHONGSHU:apify||Boolean(getSecret('XIAOHONGSHU_COLLECTOR_ENDPOINT')),INSTAGRAM:apify};}
function ensureDefaultTargets(){const status=collectorStatus();let added=0;for(const [platform,values] of Object.entries(DEFAULT_TARGETS)){if(!status[platform])continue;for(const value of values){const exists=db.prepare('SELECT id FROM social_monitor_targets WHERE platform=? AND target_type=? AND target_value=?').get(platform,'KEYWORD',value);if(exists){db.prepare('UPDATE social_monitor_targets SET enabled=1,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(exists.id);continue;}db.prepare('INSERT INTO social_monitor_targets(id,platform,target_type,target_value,enabled) VALUES(?,?,?,?,1)').run(newId('target'),platform,'KEYWORD',value);added++;}}return added;}
function localBase(){return `http://127.0.0.1:${process.env.PORT||4100}`;}
async function analyzePost(postId){console.log(`[DiscoveryAuto][ANALYZE] start post=${postId}`);const r=await fetch(`${localBase()}/api/discovery/posts/${encodeURIComponent(postId)}/analyze`,{method:'POST',headers:{'content-type':'application/json'},body:'{}',signal:AbortSignal.timeout(180000)});const text=await r.text();if(!r.ok){console.error(`[DiscoveryAuto][ANALYZE][FAILED] post=${postId} status=${r.status} reason=${text.slice(0,1200)}`);throw new Error(text||`분석 실패 (${r.status})`);}const parsed=JSON.parse(text||'{}');console.log(`[DiscoveryAuto][ANALYZE] success post=${postId} status=${parsed.status||'OK'} matches=${Array.isArray(parsed.matches)?parsed.matches.length:0}`);return parsed;}
function analysisQueue(){return db.prepare(`SELECT p.id,p.status,(SELECT COUNT(*) FROM social_job_logs l WHERE l.post_id=p.id AND l.stage='ANALYSIS_FAILED') AS failure_count FROM social_posts p WHERE COALESCE(p.video_url,'')<>'' AND (p.status='DISCOVERED' OR (p.status='ANALYSIS_FAILED' AND (SELECT COUNT(*) FROM social_job_logs l2 WHERE l2.post_id=p.id AND l2.stage='ANALYSIS_FAILED') < ?)) ORDER BY CASE WHEN p.status='ANALYSIS_FAILED' THEN 0 ELSE 1 END,p.updated_at DESC,p.created_at DESC LIMIT 20`).all(MAX_ANALYSIS_FAILURES);}
async function executeOneClick(){runState.running=true;runState.stage='COLLECTING';runState.message='Apify에서 Douyin·Xiaohongshu와 등록된 Instagram 벤치마킹 계정을 수집하고 있습니다';runState.startedAt=new Date().toISOString();runState.finishedAt=null;runState.newPosts=0;runState.queued=0;runState.retryQueued=0;runState.processed=0;runState.succeeded=0;runState.failed=0;runState.currentPostId=null;runState.lastError=null;console.log('[DiscoveryAuto] one-click started');try{ensureDefaultTargets();const before=Number(db.prepare('SELECT COUNT(*) FROM social_posts').pluck().get()||0);await runSocialMonitorOnce();const after=Number(db.prepare('SELECT COUNT(*) FROM social_posts').pluck().get()||0);runState.newPosts=Math.max(0,after-before);runState.totalPosts=after;console.log(`[DiscoveryAuto] collection done new=${runState.newPosts} total=${after}`);const posts=analysisQueue();runState.queued=posts.length;runState.retryQueued=posts.filter(p=>p.status==='ANALYSIS_FAILED').length;runState.stage='ANALYZING';runState.message=posts.length?`영상 ${posts.length}개를 자동 분석하고 있습니다${runState.retryQueued?` · 재시도 ${runState.retryQueued}개`:''}`:'새로 분석하거나 재시도할 영상이 없습니다';console.log(`[DiscoveryAuto] analysis queue=${posts.length} retry=${runState.retryQueued}`);for(const p of posts){runState.currentPostId=p.id;if(p.status==='ANALYSIS_FAILED')console.log(`[DiscoveryAuto] retrying failed post=${p.id} previousFailures=${Number(p.failure_count||0)}`);try{await analyzePost(p.id);runState.succeeded++;}catch(err){runState.failed++;runState.lastError=String(err?.message||err).slice(0,500);console.error(`[DiscoveryAuto] post failed post=${p.id} reason=${runState.lastError}`);}finally{runState.processed++;}}runState.stage='DONE';runState.message=`완료 · 영상 ${runState.processed}개 처리 · 성공 ${runState.succeeded} · 실패 ${runState.failed}`;console.log(`[DiscoveryAuto] done processed=${runState.processed} success=${runState.succeeded} failed=${runState.failed}`);}catch(err){runState.stage='FAILED';runState.lastError=String(err?.message||err);runState.message=`자동 실행 실패 · ${runState.lastError}`;console.error(`[DiscoveryAuto][FAILED] ${runState.lastError}`,err);}finally{runState.running=false;runState.currentPostId=null;runState.finishedAt=new Date().toISOString();}}
discoveryAutoRouter.get('/status',(_req,res)=>{const collectors=collectorStatus();res.json({collectors,ready:collectors.DOUYIN||collectors.XIAOHONGSHU||collectors.INSTAGRAM,services:{apify:collectors.APIFY,openai:!!getSecret('OPENAI_API_KEY'),serpapi:!!getSecret('SERPAPI_API_KEY'),coupang:!!getSecret('COUPANG_ACCESS_KEY')&&!!getSecret('COUPANG_SECRET_KEY'),publicBaseUrl:!!getSecret('PUBLIC_BASE_URL')},activeTargets:Number(db.prepare('SELECT COUNT(*) FROM social_monitor_targets WHERE enabled=1').pluck().get()||0),instagramTargets:Number(db.prepare("SELECT COUNT(*) FROM social_monitor_targets WHERE enabled=1 AND platform='INSTAGRAM'").pluck().get()||0),posts:Number(db.prepare('SELECT COUNT(*) FROM social_posts').pluck().get()||0),run:{...runState}});});
discoveryAutoRouter.post('/run',(req,res)=>{const collectors=collectorStatus();if(!collectors.APIFY&&!collectors.DOUYIN&&!collectors.XIAOHONGSHU)return res.status(503).json({error:'Apify API Token을 먼저 저장해 주세요.'});if(!getSecret('OPENAI_API_KEY'))return res.status(503).json({error:'OpenAI API Key를 먼저 저장해 주세요. 상품 판독과 Instagram 대본 재작성에 필요합니다.'});if(!getSecret('SERPAPI_API_KEY'))return res.status(503).json({error:'SerpApi Key를 먼저 저장해 주세요.'});if(!getSecret('COUPANG_ACCESS_KEY')||!getSecret('COUPANG_SECRET_KEY'))return res.status(503).json({error:'쿠팡파트너스 Access Key와 Secret Key를 먼저 저장해 주세요.'});if(!getSecret('PUBLIC_BASE_URL'))return res.status(503).json({error:'Public Base URL을 먼저 저장해 주세요.'});if(runState.running)return res.status(409).json({error:'이미 자동 작업이 진행 중입니다.',run:{...runState}});setImmediate(()=>executeOneClick());res.status(202).json({ok:true,status:'STARTED',message:'중국 SNS + Instagram 수집부터 쿠팡 매칭까지 자동 작업을 시작했습니다.'});});
