const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];let currentId=null;let pollTimer=null;const statusProgress={DRAFT:8,QUEUED:15,ANALYZING:25,SCRIPT_READY:38,PLANNING:48,MEDIA_READY:62,TTS_READY:72,CAPTIONS_READY:82,RENDERING:92,READY:100,FAILED:100};
function setTab(name){$$('.tab-panel').forEach(x=>x.classList.remove('active'));$$('.nav-btn').forEach(x=>x.classList.remove('active'));$('#tab-'+name)?.classList.add('active');$(`.nav-btn[data-tab="${name}"]`)?.classList.add('active');if(name==='settings')loadSettingsStatus()}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
function svc(el,ok){if(!el)return;el.textContent=ok?'● 연결됨':'● 미설정';el.className=ok?'service-ok':'service-no'}
async function health(){try{const r=await fetch('/api/health');if(!r.ok)throw 0;const j=await r.json();$('#connStatus').textContent='서버 연결됨';$('#connStatus').className='conn-badge conn-yes';svc($('#svcOpenai'),j.services?.openai);svc($('#svcPexels'),j.services?.pexels);svc($('#svcYoutube'),j.services?.youtube);svc($('#svcFfmpeg'),j.services?.ffmpeg);svc($('#svcFfprobe'),j.services?.ffprobe)}catch{$('#connStatus').textContent='서버 연결 실패';$('#connStatus').className='conn-badge conn-no'}}
async function loadSettingsStatus(){try{const r=await fetch('/api/settings/status');const j=await r.json();if(!r.ok)throw new Error(j.error||'설정 조회 실패');svc($('#svcOpenai'),j.services?.openai);svc($('#svcPexels'),j.services?.pexels);svc($('#svcYoutube'),j.services?.youtube);$('#pinSetupBox')?.classList.toggle('hidden',!!j.pinConfigured);$('#apiKeyBox')?.classList.toggle('hidden',!j.pinConfigured)}catch(e){if($('#settingsMsg')){$('#settingsMsg').className='msg error';$('#settingsMsg').textContent=e.message}}}
$('#setupPinBtn')?.addEventListener('click',async()=>{const pin=$('#newAdminPin').value;const btn=$('#setupPinBtn');btn.disabled=true;try{const r=await fetch('/api/settings/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin})});const j=await r.json();if(!r.ok)throw new Error(j.error||'PIN 설정 실패');$('#newAdminPin').value='';await loadSettingsStatus();$('#settingsMsg').textContent='관리자 PIN이 설정되었습니다.'}catch(e){alert(e.message)}finally{btn.disabled=false}});
$('#saveApiKeysBtn')?.addEventListener('click',async()=>{const pin=$('#adminPin').value.trim();const keys={};if($('#openaiKey').value.trim())keys.OPENAI_API_KEY=$('#openaiKey').value.trim();if($('#pexelsKey').value.trim())keys.PEXELS_API_KEY=$('#pexelsKey').value.trim();if($('#youtubeKey').value.trim())keys.YOUTUBE_API_KEY=$('#youtubeKey').value.trim();const msg=$('#settingsMsg'),btn=$('#saveApiKeysBtn');msg.className='msg';msg.textContent='저장 중…';btn.disabled=true;try{if(!pin)throw new Error('관리자 PIN을 입력해 주세요.');if(!Object.keys(keys).length)throw new Error('저장할 API Key를 하나 이상 입력해 주세요.');const r=await fetch('/api/settings/keys',{method:'PUT',headers:{'content-type':'application/json','x-admin-pin':pin},body:JSON.stringify({keys})});const j=await r.json();if(!r.ok)throw new Error(j.error||'저장 실패');$('#openaiKey').value='';$('#pexelsKey').value='';$('#youtubeKey').value='';msg.textContent='API Key 저장 완료';await health();await loadSettingsStatus()}catch(e){msg.className='msg error';msg.textContent=e.message}finally{btn.disabled=false}});
$$('.api-eye').forEach(b=>b.addEventListener('click',()=>{const el=$('#'+b.dataset.target);if(!el)return;const show=el.type==='password';el.type=show?'text':'password';b.textContent=show?'숨김':'보기'}));
function ids(){try{return JSON.parse(localStorage.getItem('globalShortsProjects')||'[]')}catch{return[]}}
function saveId(id){const a=[id,...ids().filter(x=>x!==id)].slice(0,30);localStorage.setItem('globalShortsProjects',JSON.stringify(a))}
async function loadProject(id){const r=await fetch('/api/projects/'+encodeURIComponent(id));if(!r.ok)throw new Error('프로젝트 조회 실패');return r.json()}
async function refreshList(){const list=$('#projectList');const all=ids();if(!all.length){list.innerHTML='<p class="empty">아직 프로젝트가 없습니다</p>';updateStats([]);return}const rows=[];for(const id of all){try{rows.push(await loadProject(id))}catch{}}updateStats(rows);list.innerHTML=rows.length?rows.map(x=>card(x.project)).join(''):'<p class="empty">프로젝트를 불러오지 못했습니다</p>';$$('.project-card').forEach(el=>el.onclick=()=>openProject(el.dataset.id))}
function card(p){const c=p.status==='READY'?'ready':p.status==='FAILED'?'failed':'';return `<div class="project-card" data-id="${p.id}"><div class="project-card-top"><p class="project-topic">${esc(p.topic||'Untitled')}</p><span class="status-pill ${c}">${esc(p.status||'DRAFT')}</span></div><div class="project-meta">${esc(p.voice_mode||'AI_TTS')} · ${esc(p.created_at||'')}</div></div>`}
function updateStats(rows){$('#statTotal').textContent=rows.length;$('#statReady').textContent=rows.filter(x=>x.project.status==='READY').length;$('#statRunning').textContent=rows.filter(x=>!['READY','FAILED','DRAFT'].includes(x.project.status)).length}
async function openProject(id){currentId=id;const d=await loadProject(id);showCurrent(d);renderDetail(d);renderMetadata(d);setTab(d.project.status==='READY'?'preview':'create');startPoll()}
function showCurrent(d){const p=d.project;$('#currentProject').classList.remove('hidden');$('#currentTopic').textContent=p.topic;$('#currentStatus').textContent=p.status;$('#currentStatus').className='status-pill '+(p.status==='READY'?'ready':p.status==='FAILED'?'failed':'');$('#progressBar').style.width=(statusProgress[p.status]||20)+'%';$('#progressText').textContent=statusLabel(p.status);$('#runBtn').classList.toggle('hidden',!['DRAFT','FAILED'].includes(p.status));if(p.error_message){$('#progressText').innerHTML+=`<div class="error-box">${esc(p.error_message)}</div>`}}
function renderDetail(d){const box=$('#detailBox');let h='';if(d.script)h+=`<div class="script-box"><h3>AI SCRIPT</h3><p>${esc(d.script.script||d.script.hook||'')}</p></div>`;(d.scenes||[]).forEach(s=>h+=`<div class="scene-box"><h3>SCENE ${s.scene_order}</h3><p>${esc(s.narration||'')}</p><p style="color:#9a8ea6;margin-top:6px">${esc(s.visual_query||'')}</p></div>`);box.innerHTML=h||'<p class="empty">아직 생성된 대본/Scene이 없습니다</p>';const render=(d.renders||[]).find(r=>r.status==='READY'||r.file_path);const ph=$('.phone-frame');if(render?.file_path){let src=render.file_path.replace(/^.*?storage[\\/]/,'/storage/').replaceAll('\\','/');ph.innerHTML=`<video controls playsinline src="${esc(src)}"></video>`}else ph.innerHTML='<div class="phone-placeholder">완성된 영상이 생성되면<br>여기에 표시됩니다</div>'}
function renderMetadata(d){const box=$('#metadataBox');if(!box)return;const m=d.publication;if(!m){box.innerHTML='<p class="empty">영상이 완성되면 제목, 설명, 해시태그가 자동 생성됩니다.</p>';return}const tags=Array.isArray(m.hashtags)?m.hashtags:[];const all=[m.title,m.description,tags.join(' ')].filter(Boolean).join('\n\n');box.innerHTML=`<div class="meta-field"><div class="meta-label">TITLE</div><div class="meta-value" id="metaTitle">${esc(m.title||'')}</div></div><div class="meta-field"><div class="meta-label">DESCRIPTION</div><div class="meta-value" id="metaDescription">${esc(m.description||'')}</div></div><div class="meta-field"><div class="meta-label">HASHTAGS</div><div class="tag-row">${tags.map(t=>`<span class="tag-chip">${esc(t)}</span>`).join('')}</div></div><div class="copy-row"><button class="btn-secondary copy-btn" data-copy="title">제목 복사</button><button class="btn-secondary copy-btn" data-copy="hashtags">해시태그 복사</button><button class="btn-primary copy-btn" data-copy="all">전체 복사</button></div>`;$$('.copy-btn').forEach(b=>b.onclick=async()=>{const type=b.dataset.copy;const text=type==='title'?(m.title||''):type==='hashtags'?tags.join(' '):all;try{await navigator.clipboard.writeText(text);const old=b.textContent;b.textContent='복사됨';setTimeout(()=>b.textContent=old,1200)}catch{alert(text)}})}
function statusLabel(s){return({DRAFT:'실행 준비 완료',QUEUED:'작업 대기 중',ANALYZING:'AI 대본 생성 중',SCRIPT_READY:'영어 대본 생성 완료',PLANNING:'Scene 구성 중',MEDIA_READY:'스톡 영상 준비 완료',TTS_READY:'TTS 생성 완료',CAPTIONS_READY:'자막 정렬 완료',RENDERING:'9:16 영상 렌더링 중',READY:'영상 생성 완료',FAILED:'생성 실패'}[s]||s)}
$('#createForm').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#createMsg');msg.className='msg';msg.textContent='프로젝트 생성 중…';try{const r=await fetch('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topic:$('#topicInput').value.trim(),source_type:'TOPIC',voice_mode:$('#voiceMode').value})});const j=await r.json();if(!r.ok)throw new Error(j.error||'생성 실패');currentId=j.id;saveId(j.id);msg.textContent='프로젝트 생성 완료';await openProject(j.id)}catch(err){msg.className='msg error';msg.textContent=err.message}});
$('#runBtn').addEventListener('click',async()=>{if(!currentId)return;$('#runBtn').disabled=true;try{const r=await fetch(`/api/projects/${encodeURIComponent(currentId)}/run`,{method:'POST'});if(!r.ok)throw new Error('실행 실패');startPoll()}catch(e){$('#progressText').textContent=e.message}finally{$('#runBtn').disabled=false}});
function startPoll(){clearInterval(pollTimer);pollTimer=setInterval(async()=>{if(!currentId)return;try{const d=await loadProject(currentId);showCurrent(d);renderDetail(d);renderMetadata(d);if(['READY','FAILED'].includes(d.project.status)){clearInterval(pollTimer);refreshList();if(d.project.status==='READY')setTab('preview')}}catch{}},2500)}
$('#trendSearchBtn')?.addEventListener('click',async()=>{const btn=$('#trendSearchBtn'),msg=$('#trendMsg'),box=$('#trendResults');btn.disabled=true;msg.className='msg';msg.textContent='해외 바이럴 후보 수집 중…';box.innerHTML='';try{const qs=new URLSearchParams({region:$('#trendRegion').value,category:$('#trendCategory').value,days:$('#trendDays').value});const r=await fetch('/api/trends?'+qs);const j=await r.json();if(!r.ok)throw new Error(j.error||'검색 실패');msg.textContent=j.items?.length?`${j.items.length}개 후보를 찾았습니다`:'조건에 맞는 후보가 없습니다';box.innerHTML=(j.items||[]).map((x,i)=>`<div class="trend-card"><img class="trend-thumb" src="${esc(x.thumbnail)}" alt=""><div><div class="trend-score">Viral ${x.score}점</div><div class="trend-title">${esc(x.title)}</div><div class="trend-meta">${esc(x.channelTitle)} · 조회 ${fmt(x.views)} · 채널 ${fmt(x.subscribers)} · ${Math.round(x.duration)}초<br>시간당 약 ${fmt(x.velocity)}뷰 · 채널 대비 ${x.ratio}배</div><div class="trend-actions"><button type="button" class="btn-primary trend-use" data-title="${attr(x.title)}">이 소재로 만들기</button><a class="btn-secondary" href="${esc(x.url)}" target="_blank" rel="noopener">원본 보기</a></div></div></div>`).join('');$$('.trend-use').forEach(b=>b.onclick=()=>{$('#topicInput').value=b.dataset.title||'';$('#topicInput').scrollIntoView({behavior:'smooth',block:'center'});$('#topicInput').focus()})}catch(e){msg.className='msg error';msg.textContent=e.message}finally{btn.disabled=false}});
$('#refreshBtn').onclick=refreshList;function fmt(n){n=Number(n||0);if(n>=1e6)return (n/1e6).toFixed(1)+'M';if(n>=1e3)return (n/1e3).toFixed(1)+'K';return String(Math.round(n))}function attr(v){return esc(v).replace(/`/g,'&#96;')}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}health();refreshList();loadSettingsStatus();
