const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];let currentId=null;let pollTimer=null;const statusProgress={DRAFT:8,QUEUED:15,ANALYZING:25,SCRIPT_READY:38,PLANNING:48,MEDIA_READY:62,TTS_READY:72,CAPTIONS_READY:82,RENDERING:92,READY:100,FAILED:100};
function setTab(name){$$('.tab-panel').forEach(x=>x.classList.remove('active'));$$('.nav-btn').forEach(x=>x.classList.remove('active'));$('#tab-'+name)?.classList.add('active');$(`.nav-btn[data-tab="${name}"]`)?.classList.add('active')}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
async function health(){try{const r=await fetch('/api/health');if(!r.ok)throw 0;$('#connStatus').textContent='서버 연결됨';$('#connStatus').className='conn-badge conn-yes'}catch{$('#connStatus').textContent='서버 연결 실패';$('#connStatus').className='conn-badge conn-no'}}
function ids(){try{return JSON.parse(localStorage.getItem('globalShortsProjects')||'[]')}catch{return[]}}
function saveId(id){const a=[id,...ids().filter(x=>x!==id)].slice(0,30);localStorage.setItem('globalShortsProjects',JSON.stringify(a))}
async function loadProject(id){const r=await fetch('/api/projects/'+encodeURIComponent(id));if(!r.ok)throw new Error('프로젝트 조회 실패');return r.json()}
async function refreshList(){const list=$('#projectList');const all=ids();if(!all.length){list.innerHTML='<p class="empty">아직 프로젝트가 없습니다</p>';updateStats([]);return}const rows=[];for(const id of all){try{rows.push(await loadProject(id))}catch{}}updateStats(rows);list.innerHTML=rows.length?rows.map(x=>card(x.project)).join(''):'<p class="empty">프로젝트를 불러오지 못했습니다</p>';$$('.project-card').forEach(el=>el.onclick=()=>openProject(el.dataset.id))}
function card(p){const c=p.status==='READY'?'ready':p.status==='FAILED'?'failed':'';return `<div class="project-card" data-id="${p.id}"><div class="project-card-top"><p class="project-topic">${esc(p.topic||'Untitled')}</p><span class="status-pill ${c}">${esc(p.status||'DRAFT')}</span></div><div class="project-meta">${esc(p.voice_mode||'AI_TTS')} · ${esc(p.created_at||'')}</div></div>`}
function updateStats(rows){$('#statTotal').textContent=rows.length;$('#statReady').textContent=rows.filter(x=>x.project.status==='READY').length;$('#statRunning').textContent=rows.filter(x=>!['READY','FAILED','DRAFT'].includes(x.project.status)).length}
async function openProject(id){currentId=id;const d=await loadProject(id);showCurrent(d);renderDetail(d);setTab(d.project.status==='READY'?'preview':'create');startPoll()}
function showCurrent(d){const p=d.project;$('#currentProject').classList.remove('hidden');$('#currentTopic').textContent=p.topic;$('#currentStatus').textContent=p.status;$('#currentStatus').className='status-pill '+(p.status==='READY'?'ready':p.status==='FAILED'?'failed':'');$('#progressBar').style.width=(statusProgress[p.status]||20)+'%';$('#progressText').textContent=statusLabel(p.status);$('#runBtn').classList.toggle('hidden',!['DRAFT','FAILED'].includes(p.status));if(p.error_message){$('#progressText').innerHTML+=`<div class="error-box">${esc(p.error_message)}</div>`}}
function renderDetail(d){const box=$('#detailBox');let h='';if(d.script)h+=`<div class="script-box"><h3>AI SCRIPT</h3><p>${esc(d.script.script||d.script.hook||'')}</p></div>`;(d.scenes||[]).forEach(s=>h+=`<div class="scene-box"><h3>SCENE ${s.scene_order}</h3><p>${esc(s.narration||'')}</p><p style="color:#9a8ea6;margin-top:6px">${esc(s.visual_query||'')}</p></div>`);box.innerHTML=h||'<p class="empty">아직 생성된 대본/Scene이 없습니다</p>';const render=(d.renders||[]).find(r=>r.status==='READY'||r.file_path);const ph=$('.phone-frame');if(render?.file_path){let src=render.file_path.replace(/^.*?storage[\\/]/,'/storage/').replaceAll('\\','/');ph.innerHTML=`<video controls playsinline src="${esc(src)}"></video>`}else ph.innerHTML='<div class="phone-placeholder">완성된 영상이 생성되면<br>여기에 표시됩니다</div>'}
function statusLabel(s){return({DRAFT:'실행 준비 완료',QUEUED:'작업 대기 중',ANALYZING:'소재 분석 중',SCRIPT_READY:'영어 대본 생성 완료',PLANNING:'Scene 구성 중',MEDIA_READY:'스톡 영상 준비 완료',TTS_READY:'TTS 생성 완료',CAPTIONS_READY:'자막 정렬 완료',RENDERING:'9:16 영상 렌더링 중',READY:'영상 생성 완료',FAILED:'생성 실패'}[s]||s)}
$('#createForm').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#createMsg');msg.className='msg';msg.textContent='프로젝트 생성 중…';try{const r=await fetch('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topic:$('#topicInput').value.trim(),source_type:'TOPIC',voice_mode:$('#voiceMode').value})});const j=await r.json();if(!r.ok)throw new Error(j.error||'생성 실패');currentId=j.id;saveId(j.id);msg.textContent='프로젝트 생성 완료';await openProject(j.id)}catch(err){msg.className='msg error';msg.textContent=err.message}});
$('#runBtn').addEventListener('click',async()=>{if(!currentId)return;$('#runBtn').disabled=true;try{const r=await fetch(`/api/projects/${encodeURIComponent(currentId)}/run`,{method:'POST'});if(!r.ok)throw new Error('실행 실패');startPoll()}catch(e){$('#progressText').textContent=e.message}finally{$('#runBtn').disabled=false}});
function startPoll(){clearInterval(pollTimer);pollTimer=setInterval(async()=>{if(!currentId)return;try{const d=await loadProject(currentId);showCurrent(d);renderDetail(d);if(['READY','FAILED'].includes(d.project.status)){clearInterval(pollTimer);refreshList();if(d.project.status==='READY')setTab('preview')}}catch{}},2500)}
$('#refreshBtn').onclick=refreshList;function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}health();refreshList();
