import { getSecret } from '../../lib/settingsStore.js';
const PEXELS_SEARCH_URL = 'https://api.pexels.com/videos/search';
const MIN_DURATION = 2;
const MAX_DURATION = 60;

function tokens(text=''){
  return new Set(String(text||'').toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>=3));
}
function overlapScore(a,b){
  const A=tokens(a),B=tokens(b); if(!A.size||!B.size) return 0;
  let hit=0; for(const x of A) if(B.has(x)) hit++;
  return hit/Math.max(1,Math.min(A.size,B.size));
}
function scoreCandidate(video, sceneDuration, continuity={}) {
  let score = 0;
  const files = video.video_files || [];
  if (files.some((f) => f.height > f.width) || video.height > video.width) score += 0.25;
  const maxHeight = Math.max(0, ...files.map(f=>f.height||0));
  if (maxHeight >= 1080) score += 0.15; else if (maxHeight >= 720) score += 0.08;
  const d = video.duration || 0;
  if (d < MIN_DURATION || d > MAX_DURATION) return 0;
  score += d >= sceneDuration ? 0.25 : 0.25 * d / sceneDuration;
  score += Math.max(0, 0.15 - (video._rank || 0) * 0.03);

  // Continuity weighting (up to +0.20): prefer the same creator/source style when
  // possible, and favor candidate metadata whose URL/creator text overlaps with the
  // shared story/continuity anchors generated by ScenePlanner.
  const creator=String(video?.user?.name||'');
  const metaText=[video?.url,creator].filter(Boolean).join(' ');
  if(continuity.previousCreator && creator && creator===continuity.previousCreator) score += 0.08;
  const continuityText=[continuity.anchor,continuity.previousQuery,continuity.keywords?.join(' ')].filter(Boolean).join(' ');
  score += Math.min(0.12, overlapScore(metaText,continuityText)*0.12);
  return Math.round(score * 1000) / 1000;
}
function chooseFile(files=[]) {
  const portrait = files.filter(f=>f.height>f.width).sort((a,b)=>Math.abs((a.width||0)-1080)+Math.abs((a.height||0)-1920) - (Math.abs((b.width||0)-1080)+Math.abs((b.height||0)-1920)));
  const pool = portrait.length ? portrait : files;
  return pool.find(f=>(f.height||0)>=720) || pool[0] || null;
}
export async function searchPexels(query, sceneDuration=3, options={}) {
  const apiKey = getSecret('PEXELS_API_KEY');
  if (!apiKey) throw new Error('PEXELS_API_KEY가 설정되어 있지 않습니다. 설정 화면에서 입력해 주세요.');
  const url = `${PEXELS_SEARCH_URL}?query=${encodeURIComponent(query)}&orientation=portrait&per_page=${options.maxResults||10}`;
  const res = await fetch(url,{headers:{Authorization:apiKey}});
  if(!res.ok) throw new Error(`Pexels API 오류 (${res.status})`);
  const data=await res.json();
  const continuity=options.continuity||{};
  const candidates=(data.videos||[]).map((v,i)=>{
    v._rank=i; const f=chooseFile(v.video_files); if(!f) return null;
    return {
      externalId:String(v.id),provider:'pexels',previewUrl:v.image,downloadUrl:f.link,duration:v.duration,width:f.width,height:f.height,
      licenseType:'Pexels License',creatorName:String(v?.user?.name||''),sourceUrl:String(v?.url||''),
      score:scoreCandidate(v,sceneDuration,continuity)
    };
  }).filter(Boolean).filter(c=>c.score>0).sort((a,b)=>b.score-a.score).slice(0,5);
  return {candidates,fallbackNeeded:candidates.length===0};
}
