import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { initSchema } from './db/db.js';
import { projectsRouter } from './routes/projects.js';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
initSchema();
const app = express();
app.use(cors());
app.use(express.json({ limit: '5mb' }));
app.use('/api/projects', projectsRouter);
app.use('/storage', express.static(path.join(__dirname, '..', 'storage')));
app.use('/', express.static(path.join(__dirname, '..', 'admin')));
app.get('/api/health', (_req, res) => res.json({ ok: true }));
const port = process.env.PORT || 4100;
app.listen(port, () => console.log(`yt-shorts-global API listening on :${port}`));
